### ISSUE TITLE
Crashes on launch with Eldritch Arcane Workings mod, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [cleannrooster/aureatereliquary#1]
Logs: https://mclo.gs/VpcUeTV

**Comment by cleannrooster** [comment]
I changed the mixin file name to hopefully fix this. Thanks for bringing it up.

**Comment by cleannrooster** [comment]
The mod now works with the version that the mod author for EAW uploaded 6 days ago, whatever he did today seems to have made his mixin config unreadable.

**Comment by TalEdd** [comment]
Thanks for the update! 😊
